### ISSUE TITLE
Put SimPyClassic docs on ReadTheDocs.

### ISSUE THREAD

**Issue by dythya** [SimPyClassic/SimPyClassic#38]
We should put the docs on the ReadTheDocs when we release.

SimPy docs are here as well.

**Comment by rhysmdnz** [comment]
Already at http://simpyclassic.readthedocs.io/en/latest/

**Comment by dythya** [comment]
Cool. Sum up our discussion I will 

- [x] create a basic web page on git hub wiki 

- [x] Create a front page for the read docs rather than the example page

- [x] Fix up all the links

**Comment by dythya** [comment]
Decided to use the main github page for the moment.
