### ISSUE TITLE
Documentation does not build

### ISSUE THREAD

**Issue by rhysmdnz** [SimPyClassic/SimPyClassic#9]
`make html` fails with the error `ModuleNotFoundError: No module named 'SimPy'`

**Comment by dythya** [comment]
@johnguant same as with pytest  it wont run unless you do a pip install .
It can not find the library.
So I guess you could consider that broken as well.

**Comment by dythya** [comment]
Also some lex warnings
I'll open a new issue

**Comment by dythya** [comment]
If the current fix does not work for you let me know what error you get.
